clc, clear; close all;
MBW_MATLAB = importNetworkFromONNX('MBW.onnx',InputDataFormats='TBC');
% analyzeNetwork(MBW_MATLAB)
lstm_layer=lstmLayer(20,...
    'InputWeights',MBW_MATLAB.Layers(3, 1).InputWeights,...
    'RecurrentWeights',MBW_MATLAB.Layers(3, 1).RecurrentWeights,...
    'Bias',MBW_MATLAB.Layers(3, 1).Bias);
fully_layer = fullyConnectedLayer(1,...
    'Weights',MBW_MATLAB.Layers(4, 1).onnx__MatMul_68,...
    'Bias',0);
layers = [ ...
    sequenceInputLayer(1)
    lstm_layer
    fully_layer]; % onnx_net.Layers(6, 1),regressionLayer
MBW_Simulink = dlnetwork(layers); %assembleNetwork(layers);
clear MBW_MATLAB;
% analyzeNetwork(MBW_Simulink)
save('MBW_Simulink.mat','MBW_Simulink');

MFD_MATLAB = importNetworkFromONNX('MFD.onnx',InputDataFormats='TBC');
% analyzeNetwork(MFD_MATLAB)
lstm_layer=lstmLayer(20,...
    'InputWeights',MFD_MATLAB.Layers(3, 1).InputWeights,...
    'RecurrentWeights',MFD_MATLAB.Layers(3, 1).RecurrentWeights,...
    'Bias',MFD_MATLAB.Layers(3, 1).Bias);
fully_layer = fullyConnectedLayer(1,...
    'Weights',MFD_MATLAB.Layers(4, 1).onnx__MatMul_68,...
    'Bias',0);
layers = [ ...
    sequenceInputLayer(1)
    lstm_layer
    fully_layer]; % onnx_net.Layers(6, 1),regressionLayer
MFD_Simulink = dlnetwork(layers); %assembleNetwork(layers);
clear MFD_MATLAB;
% analyzeNetwork(MFD_Simulink)
save('MFD_Simulink.mat','MFD_Simulink');